### ISSUE TITLE
Prometheus ServiceMonitor is not created

### ISSUE THREAD

**Issue by Lucifergene** [DataWorkflowServices/dws#222]
https://github.com/DataWorkflowServices/dws/blob/5950825b3d74e310279a51ccdbd040d5b1c07d5a/config/default/kustomization.yaml#L25

**Comment by roehrich-hpe** [comment]
Correct. We don't have the Prometheus CRDs installed on our customer's machines, and they don't want it, so we can't enable it by default.
See https://book.kubebuilder.io/reference/metrics for how you can enable it for your own purposes.
